"""Add PersonalHoleScore model

Revision ID: 067342effd80
Revises: 
Create Date: 2025-04-06 13:29:41.691204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067342effd80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_hole_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personal_score_id', sa.Integer(), nullable=False),
    sa.Column('hole_number', sa.Integer(), nullable=False),
    sa.Column('strokes', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personal_score_id'], ['personal_score.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_hole_score')
    # ### end Alembic commands ###
